apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  stabilizationWindowSeconds: 30